[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"
workingDirectory = "backend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "5001" 