"""add_extracted_content_and_content_length_columns

Revision ID: dc033d6e22d7
Revises: f3c60e1304d8
Create Date: 2025-09-12 14:59:04.380438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc033d6e22d7'
down_revision: Union[str, Sequence[str], None] = 'f3c60e1304d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('extracted_content', sa.Text(), nullable=True))
    op.add_column('uploaded_files', sa.Column('content_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'content_length')
    op.drop_column('uploaded_files', 'extracted_content')
    # ### end Alembic commands ###
