"""add_missing_processing_fields

Revision ID: f3c60e1304d8
Revises: ae55f621b1c4
Create Date: 2025-09-12 11:53:09.635061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c60e1304d8'
down_revision: Union[str, Sequence[str], None] = 'ae55f621b1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False, server_default='PENDING'))
    op.add_column('uploaded_files', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('uploaded_files', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'processed_at')
    op.drop_column('uploaded_files', 'processing_error')
    op.drop_column('uploaded_files', 'processing_status')
    # ### end Alembic commands ###
