name: Backend CI - Testing

on:
  push:
    branches: [ main, ci/**, refactor-** ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4 # Clone code from repo to runner
      
      # Setup Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v5 # Install python 3.11
        with:
          python-version: '3.11' # Cache dependencies for faster builds
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt # Path to requirements.txt

      # Install dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Run Unit Tests
      - name: Run Unit Tests
        working-directory: ./backend
        run: |
          pytest tests/unit -v --tb=short

      # Run Integration Tests
      - name: Run Integration Tests
        working-directory: ./backend
        run: |
          pytest tests/integration/ -v --tb=short
        
      # Run tests with coverage
      - name: Generate Coverage Report
        working-directory: ./backend
        run: |
          pytest tests/unit tests/integration/ --cov=app --cov-report=xml --cov-report=term-missing

      # Upload coverage to Codecov
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
        continue-on-error: true